server:
  port: 9000
application:
  title: test_app
  version: 0.0.1
spring:
  banner:
    location: 'classpath:/banner/Banner.txt'
#  datasource props
  datasource:
    url: 'jdbc:h2:mem:junit_db'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: 'pass'
#    jpa props
  jpa:
    ddl-auto: update
    database-platform: 'org.hibernate.dialect.H2Dialect'
    show_sql: true
  h2:
    console:
      enabled: true
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${SMTP-USER}
    password: ${SMTP-PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# logging props
logging:
  custom:
    smtp:
      username: ${SMTP-USER}
      password: ${SMTP-PASS}
      from: ${SMTP-USER}
      recipients:
        SMTP-EMAIL-RECIPIENT-1: ${SMTP-USER}
  level:
    root: INFO
    org.springframework.web: INFO
    org.example: ERROR
    org.hibernate: INFO
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss}] [%thread] [%-5level] %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{100} - %msg%n'
  file: logs/application-debug.log

