server:
  port: 9000

spring:
  datasource:
    url: 'jdbc:h2:mem:junit_db'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: 'pass'
  jpa:
    ddl-auto: update
    database-platform: 'org.hibernate.dialect.H2Dialect'
    show_sql: true
  h2:
    console:
      enabled: true